services:
  db:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: ${WP_DB_NAME:-wordpress}
      MARIADB_USER: ${WP_DB_USER:-wp}
      MARIADB_PASSWORD: ${WP_DB_PASS:-wp_pass}
      MARIADB_ROOT_PASSWORD: ${WP_DB_ROOT_PASS:-root_pass}
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    image: wordpress:php8.2-apache
    restart: unless-stopped
    ports:
      - "${WP_PORT:-8080}:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: ${WP_DB_NAME:-wordpress}
      WORDPRESS_DB_USER: ${WP_DB_USER:-wp}
      WORDPRESS_DB_PASSWORD: ${WP_DB_PASS:-wp_pass}
    volumes:
      - wp_data:/var/www/html
      - ../tg_gallery:/var/www/html/tg_gallery
      - ../wordpress/wp-content/themes/hamilton:/var/www/html/wp-content/themes/hamilton

  wpcli:
    image: wordpress:cli
    depends_on:
      - wordpress
      - db
    volumes:
      - wp_data:/var/www/html
      - ../wordpress/wp-content/themes/hamilton:/var/www/html/wp-content/themes/hamilton
    entrypoint: ["/bin/sh", "-lc"]

volumes:
  db_data:
  wp_data:
